[site]
title = "Minxing Huang"
description = "MSc student in Econometrics and Mathematical Economics at LSE"

[author]
name = "Minxing Huang"
title = "Master Student"
institution = "London School of Economics and Political Science"
avatar = "/bio.jpg"

[social]
email = "augusthuangmx@outlook.com"
location = "London, UK"
location_url = "https://maps.google.com"
location_details = [
  "London School of Economics and Political Science",
  "Houghton St, London WC2A 2AE, United Kingdom"
]
google_scholar = ""
orcid = ""
github = "https://github.com/AugustHuangMX"
linkedin = "https://www.linkedin.com/in/augusthuangmx/"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"


[[navigation]]
title = "Digital Garden"
type = "link"
target = "_blank"
href = "https://hzd-digital-garden.vercel.app/"


[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

#[[navigation]]
#title = "Teaching"
#type = "page"
#target = "teaching"
#href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

#[[navigation]]
#title = "Services"
#type = "page"
#target = "services"
#href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
